### Find all Content
GET http://localhost:8080/api/metadata




### Create new Content
POST http://localhost:8080/api/metadata
Content-Type: application/json

{
    "title": "Sample Article",
    "publishDate": "2024-05-27",
    "authors": ["Author One", "Author Two"],
    "content": "This is the content of the sample article."
}


### Find all files
GET http://localhost:8080/api/file




### Create new file
POST http://localhost:8080/api/file
Content-Type: application/json

{
    "title": "Title 1",
    "fileName": "File name",
    "filePath": "/path/to/file",
    "fileSize": "100",
    "authors": ["Author One", "Author Two"]
}

### Create new file
POST http://localhost:8080/api/file
Content-Type: application/json

{
    "title": "Title 1",
    "fileName": "File name",
    "filePath": "/path/to/file",
    "fileSize": "100",
    "authors": ["Author One", "Author Two"]
}

### Transfer File
POST http://localhost:8080/data/transfer?directoryName=/